CREATE TABLE users (
   id int(11) NOT NULL AUTO_INCREMENT,
   email varchar(255) UNIQUE NOT NULL,
   full_name varchar(255) NOT NULL,
   password varchar(255) NOT NULL,
   phone_number varchar(255) UNIQUE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE products (
   id int(11) NOT NULL AUTO_INCREMENT,
   name varchar(255) NOT NULL,
   price INT NOT NULL DEFAULT 0,
   stock INT NOT NULL DEFAULT 0,
   description varchar(255) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (id)
) ENGINE=InnoDB;